## YAML Template.
---
easy_admin:
    entities: 
         
        Ventas:
            class: App\Entity\Comprobante
            fields:
                - {property: total, type: money, type_options: { currency: 'ARS' } }
               
        Compras:
            class: App\Entity\Comprobante
            list:
                dql_filer: 'entity.compra = true'
            
                 
        Productos:
            class: App\Entity\Producto
            list:
                 title: '<strong>Lista</strong> de productos nuevos'
                 
     
                    
        Tipodetrabajo:
            class: App\Entity\Tipodetrabajo
            
        Estadotrabajo:
            label: Estados de Trabajo
            class: App\Entity\Estadotrabajo
            form:
              fields:
                 - descripcion
                 - { property: color, type: color,  css_class: 'col-sm-2'} 
          
            
        Alicuota:
            label: Alicuotas
            class: App\Entity\Alicuota
            
        Tipodocumento:
            label: Tipos de Documento
            class: App\Entity\TipoDocumento
            
        Tipocomprobante:
            label: Tipos de Comprobantes
            class: App\Entity\Tipocomprobante
            
        User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        LineaOrden:
            class: App\Entity\LineaOrden
            design:
                form_theme: 'horizontal'
            form:
                fields:
                    - { property: producto, type: 'easyadmin_autocomplete', icon: money}
                    - { property: cantidad, type: integer}
                   
                
                   
